[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Configure these environment variables in Netlify Site settings -> Build & deploy -> Environment
  # VITE_API_URL should point to your backend public URL (e.g. https://api.example.com)
  # VITE_API_URL = "https://api.yourdomain.com"
  # NODE_ENV = "production"

  # Optional: set analytic or monitoring keys here
  # SENTRY_DSN = "https://..."
  # LOG_LEVEL = "info"

# SPA Redirect - IMPORTANT pour React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["*"]}

# API Proxy - Décommenter et configurer après déploiement du backend
# [[redirects]]
#   from = "/api/*"
#   to = "https://tinaboutique-api.railway.app/:splat"  # <-- REMPLACER avec votre URL backend
#   status = 200
#   force = false

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
